### PR TITLE
Add rule quoted element enumerable set of options

### PR DESCRIPTION
**Pull request by racodond**

### CODE REVIEW

**Comment by racodond** [comment]
@iwarapter I'm not very happy with the title and the description of the rule. Feel free to update it.

**Comment by iwarapter** [comment]
@racodond my main concern with this is i dont want to end up forever maintaining it with the list of accepted options for the growing types.

**Comment by iwarapter** [comment]
@racodond also in the description you linked to the latest (4.x version) of the page do you know how much(if any) has changed from 3.8?

**Comment by racodond** [comment]
@iwarapter 

> my main concern with this is i dont want to end up forever maintaining it with the list of accepted options for the growing types.
> also in the description you linked to the latest (4.x version) of the page do you know how much(if any) has changed from 3.8?

It was one of my concerns when I started building this long long list... I had a look at the different versions of the type reference page then. The number of types in version 2.7 is exactly the same as in version 3.8 or 4.x. I didn't compare every parameter but I'd say that 99% are the same. And I don't think it will change that much as basic types (files, packages, users, groups, etc.) have not been evolving that much over the past years. We may have a few false negatives when new parameters will be added but we would still cover 99% of the cases, that is enough from my point of view. Just reviewing the list, let's say once a year seems enough. So, I think that it's doable to maintain a pretty up to date list.

**Pull request merged**
