### PR TITLE
Remove rules about code coverage

### PR DESCRIPTION
**Pull request by racodond**

### CODE REVIEW

**Comment by iwarapter** [comment]
I agree this is currently not useful, however this might be a possibility in the future with things like http://www.morethanseven.net/2014/01/25/code-coverage-for-puppet-modules/

**Comment by racodond** [comment]
Interesting indeed. We can have a look at it in the future.
I'm gonna fix the conflict for the branch to be merged.

**Comment by iwarapter** [comment]
@racodond Beat you to it :)

**Comment by racodond** [comment]
:-)

**Comment by iwarapter** [comment]
Also there are some Junit xml reporters for puppet unit tests, so i was going to look into adding a surefire parser to the project in the future.

**Comment by iwarapter** [comment]
Quick question, shall we create a page in the wiki to document all the future stuff we want to do, i dont wanna dig through old issues to find this thread!

**Comment by racodond** [comment]
I would create issues instead to be able to discuss those matters. You might also want to create a "long term" milestone for those issues.

**Pull request merged**
